#!/bin/bash
# Idempotent submitter for trajectory-generation batches on Polaris preemptable.
#
# Each of the 100 fields is permanently mapped (alphabetically) to one of 20
# batches (batch_00..batch_19). Each batch becomes one PBS job with
# #PBS -N tg_b<NN> — the stable name lets us answer "is this batch already in
# flight?" via a qstat name lookup.
#
# Behavior on every run:
#   1. Generate any missing PBS files in generated_pbs/ (REGEN=1 forces overwrite).
#   2. Skip batches whose tg_b<NN> job is currently in qstat (Q/R/H).      [never qdel]
#   3. Skip batches whose every field already has 100% of its tasks.
#   4. Submit the remainder, respecting the 20-job per-project preemptable cap.
#
# Env vars:
#   DRY_RUN=1   compute everything, print "[would qsub] ..." lines, do not call qsub.
#   REGEN=1     overwrite existing PBS files (use after env_specs change).
#   PREEMPTABLE_CAP=20   per-project max_queued (Polaris-default).

set -uo pipefail

# ---------------------------------------------------------------------------
# Tunables (env-overridable)
# ---------------------------------------------------------------------------
REPO=${REPO:-/home/tommicaste/projects/SynthTools}
SCRIPTS_DIR=${SCRIPTS_DIR:-$REPO/hpc/polaris_scripts}
LIB=${LIB:-$SCRIPTS_DIR/lib}
GENERATED=${GENERATED:-$SCRIPTS_DIR/generated_pbs}

TOOL_CONTENT=${TOOL_CONTENT:-/lus/eagle/projects/CausalAlign/tommicaste/tool_content}
ENV_SPECS_DIR=${ENV_SPECS_DIR:-$TOOL_CONTENT/env_specs}
OUTPUT_DIR=${OUTPUT_DIR:-$TOOL_CONTENT/tasks}
PBS_LOGS=${PBS_LOGS:-$TOOL_CONTENT/_pbs_logs}

ACCOUNT=${ACCOUNT:-CausalAlign}
QUEUE=${QUEUE:-preemptable}
WALLTIME=${WALLTIME:-08:00:00}
PREEMPTABLE_CAP=${PREEMPTABLE_CAP:-20}

# Big-job (medium queue) tunables.
BIG_QUEUE=${BIG_QUEUE:-prod}            # routing queue → medium
BIG_WALLTIME=${BIG_WALLTIME:-06:00:00}  # medium max
BIG_MAX_NODES=${BIG_MAX_NODES:-50}      # cap on per-big-job allocation
BIG_MIN_PENDING=${BIG_MIN_PENDING:-25}  # medium queue minimum nodect

DRY_RUN=${DRY_RUN:-0}
REGEN=${REGEN:-0}

mkdir -p "$GENERATED" "$PBS_LOGS"

export ENV_SPECS_DIR OUTPUT_DIR ACCOUNT

# ---------------------------------------------------------------------------
# Step 1: derive 20 batches from env_specs and (re)write PBS files
# ---------------------------------------------------------------------------
echo "=== Step 1: derive batches and write PBS files ==="
batches_tsv="$GENERATED/.batches.tsv"
python3 "$LIB/batch_status.py" list-batches > "$batches_tsv"

NUM_BATCHES=$(wc -l < "$batches_tsv")
TOTAL_FIELDS=$(awk -F'\t' '{n=split($2,a,"|"); s+=n} END{print s+0}' "$batches_tsv")
echo "  env_specs has $TOTAL_FIELDS fields → $NUM_BATCHES batches"
if (( NUM_BATCHES != 20 )); then
  echo "  WARN: expected 20 batches; the field set may have changed since last REGEN." >&2
fi

generated=0
while IFS=$'\t' read -r nn fields_pipe; do
  pbs="$GENERATED/batch_${nn}.pbs"
  ftxt="$GENERATED/batch_${nn}.fields.txt"
  IFS='|' read -r -a fields_arr <<< "$fields_pipe"
  : > "$ftxt"
  for f in "${fields_arr[@]}"; do echo "$f" >> "$ftxt"; done
  fields_block=$(printf '%s\n' "${fields_arr[@]}")
  count=${#fields_arr[@]}
  cat > "$pbs" <<EOF
#!/bin/bash
#PBS -A $ACCOUNT
#PBS -q $QUEUE
#PBS -l select=${count}:system=polaris
#PBS -l walltime=$WALLTIME
#PBS -l filesystems=home:eagle
#PBS -N tg_b${nn}
#PBS -o $PBS_LOGS/batch_${nn}.out
#PBS -e $PBS_LOGS/batch_${nn}.err

# Auto-generated by submit_pending_batches.sh.
# Batch $nn — $count fields, one per node, concurrency 5 each.

export FIELDS="$fields_block"

bash $SCRIPTS_DIR/run_traj_gen_field_per_node.sh
EOF
  chmod +x "$pbs"
  generated=$(( generated + 1 ))
done < "$batches_tsv"
echo "  regenerated: $generated PBS files (always rewritten to reflect current field ordering)"

# ---------------------------------------------------------------------------
# Step 2: query qstat once for in-flight batches and current project load
# ---------------------------------------------------------------------------
echo
echo "=== Step 2: query qstat ==="
in_flight=$(python3 "$LIB/batch_status.py" in-flight-batches | tr '\n' ' ')
done_batches=$(python3 "$LIB/batch_status.py" done-batches | tr '\n' ' ')
current=$(python3 "$LIB/batch_status.py" count-project-in-queue)
slots=$(( PREEMPTABLE_CAP - current ))
(( slots < 0 )) && slots=0
big_a_state=$(python3 "$LIB/batch_status.py" in-flight tg_big_a 2>/dev/null || true)
big_b_state=$(python3 "$LIB/batch_status.py" in-flight tg_big_b 2>/dev/null || true)
pending_a=$(python3 "$LIB/batch_status.py" pending-fields a | wc -l)
pending_b=$(python3 "$LIB/batch_status.py" pending-fields b | wc -l)
echo "  in_flight batches : ${in_flight:-(none)}"
echo "  done batches      : ${done_batches:-(none)}"
echo "  ${ACCOUNT} preemptable in-queue: $current  (cap $PREEMPTABLE_CAP)  free slots: $slots"
echo "  tg_big_a state    : ${big_a_state:-(not in flight)}   pending in half a: $pending_a"
echo "  tg_big_b state    : ${big_b_state:-(not in flight)}   pending in half b: $pending_b"

# ---------------------------------------------------------------------------
# Step 3: per-batch decision and (DRY_RUN-aware) submission
# ---------------------------------------------------------------------------
echo
echo "=== Step 3: decide and submit ==="
log_file="$PBS_LOGS/submit.log"
ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)

in_set() { local needle=$1 set=$2; [[ " $set " == *" $needle "* ]]; }

submitted=0
skip_in_flight=0
skip_done=0
skip_cap=0
skip_big_running=0

while IFS=$'\t' read -r nn _; do
  pbs="$GENERATED/batch_${nn}.pbs"
  nn_int=$((10#$nn))   # base-10 to avoid '08'/'09' octal traps

  if in_set "$nn" "$in_flight"; then
    echo "  [skip in-flight] batch_$nn"
    echo "$ts batch_$nn skip-in-flight" >> "$log_file"
    skip_in_flight=$(( skip_in_flight + 1 ))
    continue
  fi

  if in_set "$nn" "$done_batches"; then
    echo "  [skip done     ] batch_$nn"
    echo "$ts batch_$nn skip-done" >> "$log_file"
    skip_done=$(( skip_done + 1 ))
    continue
  fi

  # Half A = batches 00..09, half B = batches 10..19. If the big job for this
  # batch's half is currently RUNNING, skip the preemptable batch — the big
  # job is doing this work right now (and qdel'd this batch on its start).
  if (( nn_int < 10 )) && [[ "$big_a_state" == "R" ]]; then
    echo "  [skip big-A R  ] batch_$nn"
    echo "$ts batch_$nn skip-big-A-running" >> "$log_file"
    skip_big_running=$(( skip_big_running + 1 ))
    continue
  fi
  if (( nn_int >= 10 )) && [[ "$big_b_state" == "R" ]]; then
    echo "  [skip big-B R  ] batch_$nn"
    echo "$ts batch_$nn skip-big-B-running" >> "$log_file"
    skip_big_running=$(( skip_big_running + 1 ))
    continue
  fi

  if (( submitted >= slots )); then
    echo "  [skip cap      ] batch_$nn"
    echo "$ts batch_$nn skip-cap" >> "$log_file"
    skip_cap=$(( skip_cap + 1 ))
    continue
  fi

  if (( DRY_RUN == 1 )); then
    echo "  [would qsub    ] $pbs"
    echo "$ts batch_$nn would-submit" >> "$log_file"
    submitted=$(( submitted + 1 ))
    continue
  fi

  jobid=$(qsub "$pbs" 2>&1)
  rc=$?
  if (( rc == 0 )) && [[ -n "$jobid" ]] && [[ "$jobid" != *"qsub:"* ]]; then
    echo "  [submitted     ] batch_$nn -> $jobid"
    echo "$ts batch_$nn submitted $jobid" >> "$log_file"
    submitted=$(( submitted + 1 ))
  else
    echo "  [REJECTED      ] batch_$nn: $jobid"
    echo "$ts batch_$nn REJECTED $jobid" >> "$log_file"
    skip_cap=$(( skip_cap + 1 ))
    continue
  fi
done < "$batches_tsv"

# ---------------------------------------------------------------------------
# Step 4: big-job decisions (medium queue, up to BIG_MAX_NODES nodes)
# ---------------------------------------------------------------------------
echo
echo "=== Step 4: big jobs (queue=$BIG_QUEUE, up to ${BIG_MAX_NODES} nodes, ${BIG_WALLTIME}) ==="

big_submitted=0
big_skipped=0

for half in a b; do
  if [[ "$half" == "a" ]]; then
    pending=$pending_a; state=$big_a_state
  else
    pending=$pending_b; state=$big_b_state
  fi

  if (( pending < BIG_MIN_PENDING )); then
    echo "  [skip too-few   ] tg_big_${half} (pending=${pending}, need >=${BIG_MIN_PENDING})"
    echo "$ts tg_big_${half} skip-too-few pending=${pending}" >> "$log_file"
    big_skipped=$(( big_skipped + 1 ))
    continue
  fi
  if [[ -n "$state" ]]; then
    echo "  [skip in-flight ] tg_big_${half} (state=${state})"
    echo "$ts tg_big_${half} skip-in-flight state=${state}" >> "$log_file"
    big_skipped=$(( big_skipped + 1 ))
    continue
  fi

  nodes=$(( pending < BIG_MAX_NODES ? pending : BIG_MAX_NODES ))
  pbs="$GENERATED/big_${half}.pbs"
  cat > "$pbs" <<EOF
#!/bin/bash
#PBS -A $ACCOUNT
#PBS -q $BIG_QUEUE
#PBS -l select=${nodes}:system=polaris
#PBS -l walltime=$BIG_WALLTIME
#PBS -l filesystems=home:eagle
#PBS -N tg_big_${half}
#PBS -o $PBS_LOGS/big_${half}.out
#PBS -e $PBS_LOGS/big_${half}.err

# Auto-generated by submit_pending_batches.sh.
# Big job for half '${half}' — ${nodes} nodes for $BIG_WALLTIME.
# On start: qdel tg_b<NN> jobs in this half (one-shot), then process up to
# ${nodes} pending fields. The runner self-skips tasks already on disk,
# so any concurrent overlap with a not-yet-qdel'd preemptable batch is safe.

set -uo pipefail

echo "[big_${half}] qdel-ing tg_b<NN> jobs in half '${half}'..."
ids=\$(python3 $LIB/batch_status.py batch-jobids ${half} 2>/dev/null || true)
if [[ -n "\$ids" ]]; then
  echo "  ids: \$(echo \$ids | tr '\n' ' ')"
  echo "\$ids" | xargs -r qdel || true
  sleep 5
else
  echo "  (none in flight)"
fi

mapfile -t pending < <(python3 $LIB/batch_status.py pending-fields ${half} ${nodes})
if (( \${#pending[@]} == 0 )); then
  echo "[big_${half}] no pending fields at run time — exiting cleanly"
  exit 0
fi

export FIELDS=\$(printf '%s\n' "\${pending[@]}")
echo "[big_${half}] running \${#pending[@]} pending fields (allocation: ${nodes} nodes)"
bash $SCRIPTS_DIR/run_traj_gen_field_per_node.sh
EOF
  chmod +x "$pbs"

  if (( DRY_RUN == 1 )); then
    echo "  [would qsub     ] $pbs (select=${nodes}, half=${half})"
    echo "$ts tg_big_${half} would-submit nodes=${nodes}" >> "$log_file"
    big_submitted=$(( big_submitted + 1 ))
    continue
  fi

  jobid=$(qsub "$pbs" 2>&1)
  rc=$?
  if (( rc == 0 )) && [[ -n "$jobid" ]] && [[ "$jobid" != *"qsub:"* ]]; then
    echo "  [submitted      ] tg_big_${half} (select=${nodes}) -> $jobid"
    echo "$ts tg_big_${half} submitted $jobid nodes=${nodes}" >> "$log_file"
    big_submitted=$(( big_submitted + 1 ))
  else
    echo "  [REJECTED       ] tg_big_${half}: $jobid"
    echo "$ts tg_big_${half} REJECTED $jobid" >> "$log_file"
    big_skipped=$(( big_skipped + 1 ))
  fi
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo
echo "=== Summary ==="
if (( DRY_RUN == 1 )); then
  echo "  (DRY_RUN — nothing actually submitted)"
fi
echo "  preemptable submitted : $submitted"
echo "  in flight             : $skip_in_flight"
echo "  already done          : $skip_done"
echo "  cap-deferred          : $skip_cap"
echo "  skipped (big running) : $skip_big_running"
echo "  big jobs submitted    : $big_submitted"
echo "  big jobs skipped      : $big_skipped"
echo
echo "=== Your jobs now ==="
qstat -u "$USER" 2>/dev/null || true
