api_keys_path: configs/api_keys.json
compute_embs:
  inputs:
    - tool_content_new/tool_json
  output_dir: tool_content_new/tool_emb
  batch_size: 64
  dtype: float32
run_deduplication:
  tool_json_dir: tool_content_new/tool_json
  emb_dir: tool_content_new/tool_emb
  yaml_dir: tool_content_new/tool_yaml
  out_path: tool_content_new/tool_list.json
  out_dir: tool_content_new/deduped_tools
  taus:
    - 0.90
    - 0.85
    - 0.75
  random_seed: 42
  log_file: tool_content_new/run_deduplication.log
  log_level: INFO
  exact_ded: true
