api_keys_path: configs/api_keys.json
generate_tool_from_field:
  field_name:
    - academic_publishing_and_citations
    - accessibility_and_inclusion
  output_dir: tool_content_new/tool_yaml
  model: claude-sonnet-4-20250514
  model_provider: anthropic
  max_tokens: 15000
  temperature: 0.0
  max_subfields_per_field: 1
  max_tasks_per_subfield: 1
  subfield_gen_template_file: prompt_templates/generate_subfields/generate_subfield_template.yml
  task_gen_template_file: prompt_templates/generate_tasks/generate_tasks_template.yml
  tool_gen_template_file: prompt_templates/generate_tools/generate_tools_template.yml
  metadata_gen_template_file: prompt_templates/generate_metadata/generate_metadata_template.yml
  verbose: false
  block_yaml: true
extract_tools:
  input_dir: tool_content_new/tool_yaml
  output_dir: tool_content_new/tool_json
generate_metadata:
  template: prompt_templates/generate_metadata/generate_metadata_template.yml
  json_glob: "tool_content_new/tool_json/*.json"
  out_dir: tool_content_new/tool_metadata
  model_provider: anthropic
  model: claude-sonnet-4-20250514
  max_tokens: 2000
  temperature: 0.0
