api_keys_path: configs/api_keys.json

generate_task_metadata:
  input_yaml: tool_content_new/tool_yaml/
  out_dir: tool_content_new/task_meta
  model_provider: anthropic
  model: claude-sonnet-4-20250514
  max_tokens: 10000
  temperature: 0.0
  template: prompt_templates/generate_environment_tasks_meta_data/generate_environment_tasks_metadata_template.yml

generate_task_list:
  inputs:
    - tool_content_new/task_meta/
  tools_dir: tool_content_new/tool_json
  out_dir: tool_content_new/task_list
