task_files:
  - tool_content_new/task_curated/ecommerce_and_retail_tool_spec_43.task2.yml
  - tool_content_new/task_curated/ecommerce_and_retail_tool_spec_43.task5.yml
  - tool_content_new/task_curated/ecommerce_and_retail_tool_spec_43.task9.yml
metadata_folder: tool_content_new/tool_meta
log_folder: tool_content_new/task_simulation
agent_model: claude-sonnet-4-20250514
agent_max_tokens: 2000
agent_temperature: 0.0
max_interactions: 20
order_matters: false
prompt_template: prompt_templates/multi_turn_task_simulation/multi_turn_template.yml
api_keys_path: configs/api_keys.json
