tool_set_yml: |
  metadata:
    field_name: "ecommerce_and_retail"
    subfield: "Order Processing and Fulfillment"
    task: "Returns and refunds processing"
    tool_budget: 12
    tool_sequences:
      simple:
        - ["Return Policy Checker", "Return Request Validator", "Customer Notifier"]
        - ["Refund Calculator", "Payment Processor", "Customer Notifier"]
      medium:
        - ["Return Request Validator", "Return Label Generator", "Return Item Inspector", "Refund Calculator", "Payment Processor", "Inventory Updater", "Customer Notifier"]
        - ["Return Status Tracker", "Return Analytics Reporter", "Exception Handler"]
      complex:
        - ["Return Policy Checker", "Return Request Validator", "Return Label Generator", "Return Status Tracker", "Return Item Inspector", "Restocking Assessor", "Refund Calculator", "Payment Processor", "Inventory Updater", "Customer Notifier", "Return Analytics Reporter"]
        - ["Return Request Validator", "Return Item Inspector", "Exception Handler", "Restocking Assessor", "Refund Calculator", "Payment Processor", "Customer Notifier", "Return Status Tracker"]

  data:
    customers:
      - customer_id: "CUST001"
        name: "Alice Johnson"
        email: "alice@email.com"
        phone: "+1-555-0101"
        address: "123 Main St, Portland, OR 97205"
        segment: "premium"
        notification_preferences: ["email", "sms"]
      - customer_id: "CUST002"
        name: "Bob Smith"
        email: "bob@email.com"
        phone: "+1-555-0102"
        address: "456 Oak Ave, Seattle, WA 98101"
        segment: "standard"
        notification_preferences: ["email"]
      - customer_id: "CUST003"
        name: "Carol Davis"
        email: "carol@email.com"
        phone: "+1-555-0103"
        address: "789 Pine St, Denver, CO 80202"
        segment: "premium"
        notification_preferences: ["email", "push_notification"]

    products:
      - item_id: "ITEM001"
        name: "Wireless Bluetooth Headphones"
        category: "electronics"
        original_price: 149.99
        return_window_days: 30
        restocking_fee_rate: 0.15
      - item_id: "ITEM002"
        name: "Cotton T-Shirt Blue"
        category: "clothing"
        original_price: 29.99
        return_window_days: 60
        restocking_fee_rate: 0.00
      - item_id: "ITEM003"
        name: "Kitchen Knife Set"
        category: "home_goods"
        original_price: 89.99
        return_window_days: 45
        restocking_fee_rate: 0.10
      - item_id: "ITEM004"
        name: "Running Shoes"
        category: "footwear"
        original_price: 119.99
        return_window_days: 90
        restocking_fee_rate: 0.00

    orders:
      - order_id: "ORD001"
        customer_id: "CUST001"
        order_date: "2024-01-15"
        items: [{"item_id": "ITEM001", "quantity": 1, "price": 149.99}]
        subtotal: 149.99
        tax_amount: 12.00
        shipping_cost: 9.99
        total_amount: 171.98
        payment_method: "credit_card"
        transaction_id: "TXN001"
      - order_id: "ORD002"
        customer_id: "CUST002"
        order_date: "2024-02-01"
        items: [{"item_id": "ITEM002", "quantity": 2, "price": 29.99}, {"item_id": "ITEM003", "quantity": 1, "price": 89.99}]
        subtotal: 149.97
        tax_amount: 12.00
        shipping_cost: 15.99
        total_amount: 177.96
        payment_method: "paypal"
        transaction_id: "TXN002"
      - order_id: "ORD003"
        customer_id: "CUST003"
        order_date: "2024-02-10"
        items: [{"item_id": "ITEM004", "quantity": 1, "price": 119.99}]
        subtotal: 119.99
        tax_amount: 9.60
        shipping_cost: 0.00
        total_amount: 129.59
        payment_method: "debit_card"
        transaction_id: "TXN003"

    return_requests:
      - return_request_id: "RET001"
        order_id: "ORD001"
        customer_id: "CUST001"
        request_date: "2024-02-01"
        items: [{"item_id": "ITEM001", "quantity": 1, "reason": "defective"}]
        status: "initiated"
      - return_request_id: "RET002"
        order_id: "ORD002"
        customer_id: "CUST002"
        request_date: "2024-02-15"
        items: [{"item_id": "ITEM002", "quantity": 1, "reason": "wrong_item"}]
        status: "approved"
      - return_request_id: "RET003"
        order_id: "ORD003"
        customer_id: "CUST003"
        request_date: "2024-02-20"
        items: [{"item_id": "ITEM004", "quantity": 1, "reason": "changed_mind"}]
        status: "completed"

    warehouses:
      - warehouse_id: "WH001"
        name: "Portland Distribution Center"
        location: "Portland, OR"
        capacity: 10000
      - warehouse_id: "WH002"
        name: "Seattle Fulfillment Center"
        location: "Seattle, WA"
        capacity: 15000

    return_policies:
      electronics:
        return_window_days: 30
        restocking_fee: 0.15
        condition_threshold: 85
      clothing:
        return_window_days: 60
        restocking_fee: 0.00
        condition_threshold: 90
      home_goods:
        return_window_days: 45
        restocking_fee: 0.10
        condition_threshold: 80
      footwear:
        return_window_days: 90
        restocking_fee: 0.00
        condition_threshold: 85

    shipping_carriers:
      - carrier: "ups"
        services: ["standard", "expedited", "overnight"]
        base_cost: 8.99
      - carrier: "fedex"
        services: ["standard", "expedited", "overnight"]
        base_cost: 9.99
      - carrier: "usps"
        services: ["standard", "expedited"]
        base_cost: 6.99

  tasks:
    simple_valid:
      - task: "Process return request RET001 for customer CUST001 who purchased wireless headphones (order ORD001 from January 15, 2024) due to defective product. Check return policy eligibility, validate the request, and notify the customer of approval status."
        task_difficulty: "simple"
        number_tools_required: 3
        tools_required: ["Return Policy Checker", "Return Request Validator", "Customer Notifier"]
        task_validity: "valid"
      - task: "Calculate refund for returned wireless headphones (ITEM001) with original price $149.99, tax rate 8%, shipping cost $9.99, and 15% restocking fee. Process the refund to original credit card payment method (transaction TXN001) and notify customer CUST001."
        task_difficulty: "simple" 
        number_tools_required: 3
        tools_required: ["Refund Calculator", "Payment Processor", "Customer Notifier"]
        task_validity: "valid"

    simple_invalid:
      - task: "Process return request for a custom-made item that requires special manufacturing approval and quality certification before acceptance."
        task_difficulty: "simple"
        number_tools_required: 4
        tools_required: ["Return Policy Checker", "Return Request Validator", "Quality Certifier", "Customer Notifier"]
        task_validity: "invalid - Quality Certifier tool not available"
      - task: "Calculate refund for international return requiring currency conversion and international banking verification."
        task_difficulty: "simple"
        number_tools_required: 4
        tools_required: ["Refund Calculator", "Currency Converter", "Bank Verifier", "Payment Processor"]
        task_validity: "invalid - Currency Converter and Bank Verifier tools not available"

    medium_valid:
      - task: "Complete return processing for customer CUST002's order ORD002 containing 2 cotton t-shirts and 1 kitchen knife set. One t-shirt was wrong item (ITEM002). Validate request RET002, generate UPS standard shipping label, inspect returned item, calculate refund ($29.99 item, $12.00 tax portion, $15.99 shipping), process PayPal refund to transaction TXN002, update inventory for 1 sellable t-shirt at warehouse WH001, and notify customer."
        task_difficulty: "medium"
        number_tools_required: 7
        tools_required: ["Return Request Validator", "Return Label Generator", "Return Item Inspector", "Refund Calculator", "Payment Processor", "Inventory Updater", "Customer Notifier"]
        task_validity: "valid"
      - task: "Generate analytics report for return trends from January 1, 2024 to February 28, 2024, track status of all active returns, and handle any exceptions found in processing."
        task_difficulty: "medium"
        number_tools_required: 3
        tools_required: ["Return Status Tracker", "Return Analytics Reporter", "Exception Handler"]
        task_validity: "valid"

    medium_invalid:
      - task: "Process return with automatic quality assessment using AI imaging system and generate customs documentation for international shipping."
        task_difficulty: "medium"
        number_tools_required: 5
        tools_required: ["Return Request Validator", "AI Quality Scanner", "Return Label Generator", "Customs Generator", "Customer Notifier"]
        task_validity: "invalid - AI Quality Scanner and Customs Generator tools not available"
      - task: "Complete return with real-time inventory synchronization across multiple sales channels and social media complaint monitoring."
        task_difficulty: "medium"
        number_tools_required: 6
        tools_required: ["Return Item Inspector", "Multi-Channel Sync", "Social Media Monitor", "Refund Calculator", "Payment Processor", "Customer Notifier"]
        task_validity: "invalid - Multi-Channel Sync and Social Media Monitor tools not available"

    complex_valid:
      - task: "Execute comprehensive return processing for customer CUST003's running shoes (order ORD003, item ITEM004, $119.99, changed mind). Check 90-day footwear return policy, validate request RET003, generate FedEx expedited return label, track return status updates, inspect received shoes with detailed assessment by inspector INSP001 (packaging intact: true, accessories complete: true, condition: like_new), assess restocking eligibility with condition score 95, calculate full refund ($119.99 + $9.60 tax, no fees), process debit card refund to transaction TXN003, update inventory with 1 sellable shoe at warehouse WH002, notify customer of completion, and generate return analytics report."
        task_difficulty: "complex"
        number_tools_required: 11
        tools_required: ["Return Policy Checker", "Return Request Validator", "Return Label Generator", "Return Status Tracker", "Return Item Inspector", "Restocking Assessor", "Refund Calculator", "Payment Processor", "Inventory Updater", "Customer Notifier", "Return Analytics Reporter"]
        task_validity: "valid"
      - task: "Handle problematic return request RET004 for customer CUST001's damaged electronics order ORD004 (2 headphones ITEM001, $299.98 total). Validate return, inspect items with condition scores 60 and 40 (damaged packaging, missing accessories), escalate through exception handling, assess restocking for damaged electronics, calculate partial refunds ($149.99 each minus 20% condition deduction), process credit card refunds, notify customer of partial approval, and track final status."
        task_difficulty: "complex"
        number_tools_required: 8
        tools_required: ["Return Request Validator", "Return Item Inspector", "Exception Handler", "Restocking Assessor", "Refund Calculator", "Payment Processor", "Customer Notifier", "Return Status Tracker"]
        task_validity: "valid"

    complex_invalid:
      - task: "Process return with blockchain verification, automated legal compliance checking, and integration with third-party logistics API."
        task_difficulty: "complex"
        number_tools_required: 8
        tools_required: ["Return Request Validator", "Blockchain Verifier", "Legal Compliance Checker", "Third Party API", "Refund Calculator", "Payment Processor", "Customer Notifier", "Return Status Tracker"]
        task_validity: "invalid - Blockchain Verifier, Legal Compliance Checker, and Third Party API tools not available"
      - task: "Complete return processing with machine learning fraud detection, automated vendor notification system, and dynamic pricing optimization."
        task_difficulty: "complex"
        number_tools_required: 9
        tools_required: ["Return Request Validator", "ML Fraud Detector", "Vendor Notifier", "Return Item Inspector", "Dynamic Pricer", "Refund Calculator", "Payment Processor", "Inventory Updater", "Customer Notifier"]
        task_validity: "invalid - ML Fraud Detector, Vendor Notifier, and Dynamic Pricer tools not available"