tool_set_yml: |
  # Meta-data JSON for Tool Simulator
  {
    "field_name": "healthcare_medical",
    "subfield": "Clinical Documentation", 
    "task": "Create and update patient medical records",
    "tool_budget": 14,
    "tool_sequences": {
      "easy": [
        ["Patient Registration Tool", "Medical History Collector", "Allergy Manager"],
        ["Patient Registration Tool", "Vital Signs Recorder", "Clinical Notes Creator"]
      ],
      "medium": [
        ["Patient Registration Tool", "Vital Signs Recorder", "Clinical Notes Creator", "Diagnosis Coder", "Medication Prescriber"],
        ["Patient Registration Tool", "Clinical Notes Creator", "Procedure Documentation", "Lab Results Integrator", "Imaging Report Generator"],
        ["Patient Registration Tool", "Care Plan Developer", "Record Sharing Tool"]
      ],
      "complex": [
        ["Patient Registration Tool", "Medical History Collector", "Vital Signs Recorder", "Clinical Notes Creator", "Diagnosis Coder", "Procedure Documentation", "Lab Results Integrator", "Imaging Report Generator", "Medication Prescriber", "Allergy Manager", "Care Plan Developer", "Medical Record Validator"],
        ["Patient Registration Tool", "Clinical Notes Creator", "Diagnosis Coder", "Procedure Documentation", "Lab Results Integrator", "Imaging Report Generator", "Medication Prescriber", "Care Plan Developer", "Medical Record Validator", "Record Sharing Tool"]
      ]
    },
    "patients": [
      {
        "patient_id": "PT-001",
        "first_name": "Sarah",
        "last_name": "Johnson", 
        "date_of_birth": "1985-03-15T00:00:00Z",
        "gender": "female",
        "address": "123 Main St, Springfield, IL 62701",
        "phone_number": "217-555-0123",
        "email": "sarah.johnson@email.com",
        "insurance_provider": "Blue Cross Blue Shield",
        "insurance_id": "BCBS123456789",
        "emergency_contact_name": "Michael Johnson",
        "emergency_contact_phone": "217-555-0124"
      },
      {
        "patient_id": "PT-002", 
        "first_name": "Robert",
        "last_name": "Smith",
        "date_of_birth": "1970-08-22T00:00:00Z",
        "gender": "male",
        "address": "456 Oak Ave, Chicago, IL 60601",
        "phone_number": "312-555-0234",
        "email": "robert.smith@email.com",
        "insurance_provider": "Aetna",
        "insurance_id": "AETNA987654321",
        "emergency_contact_name": "Linda Smith",
        "emergency_contact_phone": "312-555-0235"
      },
      {
        "patient_id": "PT-003",
        "first_name": "Maria",
        "last_name": "Garcia",
        "date_of_birth": "1992-11-08T00:00:00Z", 
        "gender": "female",
        "address": "789 Pine St, Rockford, IL 61101",
        "phone_number": "815-555-0345",
        "email": "maria.garcia@email.com",
        "insurance_provider": "UnitedHealth",
        "insurance_id": "UHG456123789",
        "emergency_contact_name": "Carlos Garcia",
        "emergency_contact_phone": "815-555-0346"
      }
    ],
    "providers": [
      {
        "provider_id": "DR-001",
        "name": "Dr. Jennifer Adams",
        "specialty": "Family Medicine",
        "department": "Primary Care"
      },
      {
        "provider_id": "DR-002", 
        "name": "Dr. Michael Chen",
        "specialty": "Cardiology",
        "department": "Internal Medicine"
      },
      {
        "provider_id": "DR-003",
        "name": "Dr. Sarah Williams", 
        "specialty": "Emergency Medicine",
        "department": "Emergency"
      },
      {
        "provider_id": "DR-004",
        "name": "Dr. David Brown",
        "specialty": "Radiology", 
        "department": "Imaging"
      }
    ],
    "medications": [
      {
        "medication_name": "Lisinopril",
        "strengths": ["5mg", "10mg", "20mg"],
        "routes": ["oral"],
        "common_frequencies": ["once daily", "twice daily"],
        "indications": ["hypertension", "heart failure"]
      },
      {
        "medication_name": "Metformin", 
        "strengths": ["500mg", "850mg", "1000mg"],
        "routes": ["oral"],
        "common_frequencies": ["twice daily", "with meals"],
        "indications": ["diabetes type 2", "insulin resistance"]
      },
      {
        "medication_name": "Amoxicillin",
        "strengths": ["250mg", "500mg", "875mg"],
        "routes": ["oral"],
        "common_frequencies": ["three times daily", "every 8 hours"],
        "indications": ["bacterial infection", "pneumonia"]
      }
    ],
    "lab_tests": [
      {
        "test_name": "Complete Blood Count",
        "loinc_code": "57021-8",
        "components": [
          {"component": "WBC", "reference_range": "4.5-11.0 x10³/μL", "unit": "x10³/μL"},
          {"component": "RBC", "reference_range": "4.7-6.1 x10⁶/μL", "unit": "x10⁶/μL"},
          {"component": "Hemoglobin", "reference_range": "14.0-18.0 g/dL", "unit": "g/dL"},
          {"component": "Hematocrit", "reference_range": "42.0-52.0 %", "unit": "%"}
        ]
      },
      {
        "test_name": "Basic Metabolic Panel",
        "loinc_code": "80048-7", 
        "components": [
          {"component": "Glucose", "reference_range": "70-100 mg/dL", "unit": "mg/dL"},
          {"component": "Sodium", "reference_range": "136-145 mmol/L", "unit": "mmol/L"},
          {"component": "Potassium", "reference_range": "3.5-5.1 mmol/L", "unit": "mmol/L"},
          {"component": "Creatinine", "reference_range": "0.7-1.3 mg/dL", "unit": "mg/dL"}
        ]
      }
    ],
    "imaging_studies": [
      {
        "modality": "X-ray",
        "body_regions": ["chest", "abdomen", "extremity", "spine"],
        "common_procedures": ["Chest X-ray PA and Lateral", "Abdominal X-ray", "Hand X-ray"]
      },
      {
        "modality": "CT", 
        "body_regions": ["head", "chest", "abdomen", "spine"],
        "common_procedures": ["CT Head without contrast", "CT Chest with contrast", "CT Abdomen and Pelvis"]
      },
      {
        "modality": "MRI",
        "body_regions": ["head", "spine", "extremity"],
        "common_procedures": ["MRI Brain", "MRI Lumbar Spine", "MRI Knee"]
      }
    ],
    "diagnoses": [
      {
        "clinical_description": "Essential hypertension",
        "icd10_code": "I10",
        "category": "Cardiovascular"
      },
      {
        "clinical_description": "Type 2 diabetes mellitus without complications",
        "icd10_code": "E11.9", 
        "category": "Endocrine"
      },
      {
        "clinical_description": "Community acquired pneumonia",
        "icd10_code": "J15.9",
        "category": "Respiratory"
      },
      {
        "clinical_description": "Acute myocardial infarction", 
        "icd10_code": "I21.9",
        "category": "Cardiovascular"
      }
    ],
    "allergies": [
      {
        "allergen": "Penicillin",
        "allergen_type": "medication",
        "reaction": "Skin rash and hives",
        "severity": "moderate"
      },
      {
        "allergen": "Shellfish",
        "allergen_type": "food", 
        "reaction": "Anaphylaxis with difficulty breathing",
        "severity": "severe"
      },
      {
        "allergen": "Latex",
        "allergen_type": "environmental",
        "reaction": "Contact dermatitis",
        "severity": "mild"
      }
    ],
    "procedures": [
      {
        "procedure_name": "Colonoscopy",
        "cpt_codes": ["45378", "45380"],
        "typical_indications": ["colorectal cancer screening", "gastrointestinal bleeding"]
      },
      {
        "procedure_name": "Cardiac catheterization",
        "cpt_codes": ["93458", "93459"],
        "typical_indications": ["chest pain evaluation", "coronary artery disease"]
      }
    ]
  }

  # Task List for Agent

  ## Easy Tasks (Valid)
  **Task 1**: Create a new patient profile for John Davis, date of birth January 15, 1980, male, residing at 321 Cedar Lane, Peoria IL 61602, phone 309-555-7890, then collect his medical history including diabetes diagnosed in 2015 and hypertension since 2018, and document his penicillin allergy with moderate severity causing skin rash.
  **Task-difficulty**: easy
  **Number-tools-required**: 3  
  **Tools-required**: ["Patient Registration Tool", "Medical History Collector", "Allergy Manager"]
  **Task-validity**: valid

  **Task 2**: Register existing patient PT-001 for a routine visit, record vital signs including temperature 98.6°F (37°C), heart rate 72 bpm, blood pressure 120/80 mmHg at 2024-01-15T10:30:00Z, then create clinical notes for the encounter with Dr. Jennifer Adams (DR-001) documenting the routine checkup.
  **Task-difficulty**: easy
  **Number-tools-required**: 3
  **Tools-required**: ["Patient Registration Tool", "Vital Signs Recorder", "Clinical Notes Creator"] 
  **Task-validity**: valid

  ## Easy Tasks (Invalid)
  **Task 3**: Create a patient profile, collect medical history, and schedule their next appointment with the scheduling system.
  **Task-difficulty**: easy
  **Number-tools-required**: 3
  **Tools-required**: ["Patient Registration Tool", "Medical History Collector", "Appointment Scheduler"]
  **Task-validity**: invalid (Appointment Scheduler tool not available)

  **Task 4**: Register a patient, record vital signs, and send automated reminder messages to their phone.
  **Task-difficulty**: easy  
  **Number-tools-required**: 3
  **Tools-required**: ["Patient Registration Tool", "Vital Signs Recorder", "Message Sender"]
  **Task-validity**: invalid (Message Sender tool not available)

  ## Medium Tasks (Valid)
  **Task 5**: For patient PT-002, update their profile with new phone number 312-555-9999, record vital signs from today's visit (temperature 99.1°F/37.3°C, heart rate 88 bpm, blood pressure 140/90 mmHg, respiratory rate 16) at 2024-01-15T14:00:00Z, create clinical notes for the encounter with provider DR-002 documenting chest pain evaluation, code the diagnosis as "chest pain unspecified" using ICD-10, and prescribe Lisinopril 10mg once daily for 30 days for hypertension management.
  **Task-difficulty**: medium
  **Number-tools-required**: 5
  **Tools-required**: ["Patient Registration Tool", "Vital Signs Recorder", "Clinical Notes Creator", "Diagnosis Coder", "Medication Prescriber"]
  **Task-validity**: valid

  **Task 6**: Register patient Maria Garcia (PT-003) for a diagnostic workup, create clinical notes with provider DR-001 for evaluation of abdominal pain at 2024-01-15T11:00:00Z, document colonoscopy procedure performed on 2024-01-15T13:00:00Z with indication "abdominal pain evaluation" and findings of "normal mucosa, no polyps detected", integrate lab results for Complete Blood Count showing WBC 7.2 x10³/μL, RBC 4.8 x10⁶/μL, Hemoglobin 13.5 g/dL collected at 2024-01-15T09:00:00Z with results at 2024-01-15T12:00:00Z, and generate an imaging report for CT Abdomen without contrast performed 2024-01-15T10:00:00Z showing normal findings interpreted by DR-004.
  **Task-difficulty**: medium
  **Number-tools-required**: 5  
  **Tools-required**: ["Patient Registration Tool", "Clinical Notes Creator", "Procedure Documentation", "Lab Results Integrator", "Imaging Report Generator"]
  **Task-validity**: valid

  ## Medium Tasks (Invalid)
  **Task 7**: Create a care plan for a patient, develop treatment protocols, and integrate with hospital billing system.
  **Task-difficulty**: medium
  **Number-tools-required**: 3
  **Tools-required**: ["Care Plan Developer", "Protocol Generator", "Billing Integrator"]
  **Task-validity**: invalid (Protocol Generator and Billing Integrator tools not available)

  **Task 8**: Document a procedure, validate the record, and automatically submit insurance claims.
  **Task-difficulty**: medium
  **Number-tools-required**: 3
  **Tools-required**: ["Procedure Documentation", "Medical Record Validator", "Insurance Claim Processor"] 
  **Task-validity**: invalid (Insurance Claim Processor tool not available)

  ## Complex Tasks (Valid)
  **Task 9**: Perform comprehensive workup for new patient Emily Wilson, DOB 1978-05-20, female, 567 Elm St Springfield IL 62702, phone 217-555-4567, insurance Aetna policy AET789123456, emergency contact David Wilson 217-555-4568. Collect medical history including hypertension since 2020 and family history of diabetes (mother). Record vital signs: temperature 98.4°F (36.9°C), heart rate 76 bpm, blood pressure 150/92 mmHg, respiratory rate 18, oxygen saturation 98% at 2024-01-15T09:00:00Z. Create clinical notes with DR-001 for new patient evaluation at 2024-01-15T09:30:00Z. Code diagnosis as essential hypertension. Document echocardiogram procedure performed 2024-01-15T11:00:00Z with indication "hypertension workup" showing normal left ventricular function. Integrate Basic Metabolic Panel results: Glucose 110 mg/dL (high), Sodium 140 mmol/L, Potassium 4.2 mmol/L, Creatinine 0.9 mg/dL collected 2024-01-15T08:00:00Z with results 2024-01-15T10:00:00Z. Generate chest X-ray report from 2024-01-15T10:30:00Z showing normal cardiopulmonary findings interpreted by DR-004. Prescribe Lisinopril 5mg once daily for 90 days. Document shellfish allergy with severe anaphylaxis reaction. Create care plan for hypertension management with goals of blood pressure control and dietary modification. Validate all records for completeness.
  **Task-difficulty**: complex
  **Number-tools-required**: 12
  **Tools-required**: ["Patient Registration Tool", "Medical History Collector", "Vital Signs Recorder", "Clinical Notes Creator", "Diagnosis Coder", "Procedure Documentation", "Lab Results Integrator", "Imaging Report Generator", "Medication Prescriber", "Allergy Manager", "Care Plan Developer", "Medical Record Validator"]
  **Task-validity**: valid

  **Task 10**: Complete discharge process for patient PT-001 admitted for acute myocardial infarction. Create discharge summary notes with DR-002 for encounter ending 2024-01-15T16:00:00Z. Code final diagnosis as acute ST-elevation myocardial infarction (I21.9). Document cardiac catheterization procedure from 2024-01-14T14:00:00Z with indication "STEMI" showing 90% LAD stenosis treated with stent placement. Integrate final lab results showing Troponin 15.2 ng/mL (critical high), Creatinine 1.1 mg/dL collected 2024-01-15T06:00:00Z with results 2024-01-15T08:00:00Z. Generate echocardiogram report from 2024-01-15T10:00:00Z showing reduced ejection fraction 40% interpreted by DR-004. Prescribe discharge medications: Metoprolol 25mg twice daily for 90 days, Atorvastatin 40mg once daily for 90 days. Create cardiac rehabilitation care plan with goals of exercise tolerance improvement and risk factor modification starting 2024-01-22T00:00:00Z. Validate discharge documentation for completeness and accuracy. Share complete medical records with outpatient cardiology office (recipient ID: CARD-CLINIC-001) for continuity of care with verified patient consent.
  **Task-difficulty**: complex  
  **Number-tools-required**: 10
  **Tools-required**: ["Patient Registration Tool", "Clinical Notes Creator", "Diagnosis Coder", "Procedure Documentation", "Lab Results Integrator", "Imaging Report Generator", "Medication Prescriber", "Care Plan Developer", "Medical Record Validator", "Record Sharing Tool"]
  **Task-validity**: valid

  ## Complex Tasks (Invalid)
  **Task 11**: Perform complete patient workup, validate records, generate billing codes, process insurance claims, and schedule follow-up appointments automatically.
  **Task-difficulty**: complex
  **Number-tools-required**: 8
  **Tools-required**: ["Patient Registration Tool", "Clinical Notes Creator", "Medical Record Validator", "Billing Code Generator", "Insurance Processor", "Appointment Scheduler", "Payment Processor", "Notification System"] 
  **Task-validity**: invalid (Multiple tools not available: Billing Code Generator, Insurance Processor, Appointment Scheduler, Payment Processor, Notification System)

  **Task 12**: Create comprehensive patient record, perform medical calculations, generate treatment protocols, coordinate with external systems, and send automated patient communications.
  **Task-difficulty**: complex
  **Number-tools-required**: 7  
  **Tools-required**: ["Patient Registration Tool", "Medical Calculator", "Protocol Generator", "System Integrator", "Communication Manager", "External Data Sync", "Analytics Engine"]
  **Task-validity**: invalid (All listed tools except Patient Registration Tool are not available)